plugins {
    id 'OmtHelper.library-conventions'
    id 'maven-publish'
    id 'java-library'
    id 'signing'
}

dependencies {
    implementation project(':OmtEncodingHelperCore')
    implementation project(':OmtEncodingHelperRpr')
}

group = 'org.nato.ivct.OmtEncodingHelper.Netn'

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'Netn.lib'
            from components.java

            pom {
                name = "NETN Netn Encoding Helper Library"
                description = "Library to support NETN encoding"
                url = "https://github.com/IVCTool/OmtEncodingHelper/tree/main/Netn.lib"
                licenses {
                    license {
                        name = "The Apache License, Version 2.0"
                        url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                    }
                }
                developers {
                    developer {
                        id = "rhzg"
                        name = "Reinhard Herzog"
                        email = "reinhard.herzog@iosb.fraunhofer.de"
                    }
                }
                scm {
                    connection = "scm:git:https://github.com/IVCTool/OmtEncodingHelper/tree/main/Netn.lib.git"
                    developerConnection = "scm:git:https://github.com/IVCTool/OmtEncodingHelper/tree/main/Netn.lib-git"
                    url = "https://github.com/IVCTool/OmtEncodingHelper/tree/main/Netn.lib"
                }
            }
        }
    }
    repositories {
        maven {
            def releasesRepoUrl = "https://oss.sonatype.org/service/local/staging/deploy/maven2/"
            def snapshotsRepoUrl = "https://oss.sonatype.org/content/repositories/snapshots/"
            url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
            credentials {
                username ossrhUsername
                password ossrhPassword
            }
        }
    }
}

signing
{
    sign publishing.publications.mavenJava
}

